/**
 * Minimal Database schema type for the Supabase client. Matches
 * db/migrations/001_initial.sql. Regenerate with:
 *   supabase gen types typescript --project-id <ref> --schema public
 * once a real project is provisioned, but this hand-written shape
 * keeps the app typechecking today.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json }
  | Json[];

export type UserRoleDb = "reader" | "practitioner" | "both";

export type ProfileRow = {
  id: string;
  email: string;
  display_name: string;
  slug: string;
  role: UserRoleDb;
  credential: string | null;
  bio: string | null;
  credits_balance_cents: number;
  email_prefs: {
    engagement_requests: boolean;
    review_published: boolean;
    weekly_digest: boolean;
    product_updates: boolean;
  };
  created_at: string;
  updated_at: string;
};

export type SubmissionRow = {
  id: string;
  user_id: string;
  skill_name: string;
  domain: string;
  description: string;
  status:
    | "draft"
    | "under_review"
    | "changes_requested"
    | "published"
    | "rejected";
  editorial_note: string | null;
  published_as: string | null;
  submitted_at: string;
  updated_at: string;
};

export type ReviewRow = {
  id: string;
  reviewer_user_id: string;
  skill_name: string;
  rating: number;
  body: string;
  status: "draft" | "pending" | "published" | "rejected";
  created_at: string;
  updated_at: string;
};

export type EngagementRow = {
  id: string;
  practitioner_user_id: string;
  buyer_user_id: string | null;
  skill_name: string | null;
  buyer_display: string;
  buyer_context: string;
  amount_cents: number;
  status:
    | "requested"
    | "quoted"
    | "in_progress"
    | "delivered"
    | "paid"
    | "cancelled";
  requested_at: string;
  delivered_at: string | null;
  paid_at: string | null;
  updated_at: string;
};

export type LedgerRow = {
  id: string;
  user_id: string;
  kind:
    | "purchase"
    | "spend"
    | "earn_engagement"
    | "earn_skill_sale"
    | "editorial_grant"
    | "refund";
  amount_cents: number;
  memo: string;
  at: string;
  ref: string | null;
};

export type SavedRow = {
  user_id: string;
  skill_name: string;
  saved_at: string;
};

export type InquiryRow = {
  id: string;
  target_kind: "skill" | "practitioner";
  target_slug: string;
  buyer_name: string;
  buyer_email: string;
  buyer_company: string | null;
  buyer_role: string | null;
  timeline: string | null;
  brief: string;
  source: string | null;
  created_at: string;
};

export type ApplicationRow = {
  id: string;
  applicant_name: string;
  credential: string;
  domain: string;
  years_practice: string | null;
  verification_ref: string;
  proposed_skill: string;
  links: string | null;
  created_at: string;
};

/**
 * Table shape used by @supabase/supabase-js 2.x. `Insert` and
 * `Update` are the columns you're allowed to hand to insert()/update();
 * autogenerated columns (id, created_at, updated_at) are optional.
 */
type Auto = "id" | "created_at" | "updated_at" | "submitted_at" | "at";
type InsertOf<Row> = Partial<Pick<Row, Extract<keyof Row, Auto>>> &
  Omit<Row, Extract<keyof Row, Auto>>;
type UpdateOf<Row> = Partial<Row>;
type Table<Row> = {
  Row: Row;
  Insert: InsertOf<Row>;
  Update: UpdateOf<Row>;
  Relationships: [];
};

export type Database = {
  public: {
    Tables: {
      profiles: Table<ProfileRow>;
      submissions: Table<SubmissionRow>;
      reviews: Table<ReviewRow>;
      engagements: Table<EngagementRow>;
      ledger: Table<LedgerRow>;
      saved: Table<SavedRow>;
      inquiries: Table<InquiryRow>;
      applications: Table<ApplicationRow>;
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
