import { describe, test, expect } from "bun:test";
import * as fs from "node:fs/promises";
import * as path from "node:path";
import * as os from "node:os";
import {
  parseShasums,
  sha256File,
  verifyBinaryAgainstShasums,
} from "../src/verify";

const GOOD_SHASUMS = `
# SHASUMS256.txt for launchpad/skillz v0.1.0
# Generated by GitHub Actions on 2026-04-18.

0000000000000000000000000000000000000000000000000000000000000001  skillz-darwin-arm64
0000000000000000000000000000000000000000000000000000000000000002  skillz-darwin-x64
0000000000000000000000000000000000000000000000000000000000000003 *skillz-linux-arm64
0000000000000000000000000000000000000000000000000000000000000004  skillz-linux-x64
`;

describe("parseShasums", () => {
  test("parses a full SHASUMS256.txt", () => {
    const entries = parseShasums(GOOD_SHASUMS);
    expect(entries).toHaveLength(4);
    expect(entries[0]).toEqual({
      hash: "0000000000000000000000000000000000000000000000000000000000000001",
      file: "skillz-darwin-arm64",
    });
    expect(entries[2]!.file).toBe("skillz-linux-arm64"); // binary-mode '*' stripped
  });

  test("skips blank lines and comments", () => {
    const entries = parseShasums("\n# header\n\n");
    expect(entries).toEqual([]);
  });

  test("ignores malformed lines", () => {
    const entries = parseShasums(`notahash  x\n${"a".repeat(64)}  valid.bin`);
    expect(entries).toHaveLength(1);
    expect(entries[0]!.file).toBe("valid.bin");
  });

  test("normalizes hash to lowercase", () => {
    const text = `ABCDEF${"0".repeat(58)}  FOO.bin`;
    const entries = parseShasums(text);
    expect(entries[0]!.hash).toBe(`abcdef${"0".repeat(58)}`);
  });
});

describe("sha256File", () => {
  test("computes stable hash for a known payload", async () => {
    const dir = await fs.mkdtemp(path.join(os.tmpdir(), "skillz-verify-"));
    const file = path.join(dir, "fixture.bin");
    try {
      await fs.writeFile(file, "hello\n");
      const hex = await sha256File(file);
      // echo "hello" | sha256sum → 5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03
      expect(hex).toBe(
        "5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03",
      );
    } finally {
      await fs.rm(dir, { recursive: true, force: true });
    }
  });
});

describe("verifyBinaryAgainstShasums", () => {
  async function setup(shasumsText: string, contents: string) {
    const dir = await fs.mkdtemp(path.join(os.tmpdir(), "skillz-verify-"));
    const binaryPath = path.join(dir, "skillz-darwin-arm64");
    const shasumsPath = path.join(dir, "SHASUMS256.txt");
    await fs.writeFile(binaryPath, contents);
    await fs.writeFile(shasumsPath, shasumsText);
    return { dir, binaryPath, shasumsPath };
  }

  test("returns ok when hash matches", async () => {
    const payload = "fake binary";
    const h = await sha256File(
      await fs.writeFile(path.join(os.tmpdir(), "t"), payload).then(async () => {
        const p = path.join(os.tmpdir(), "t");
        return p;
      }),
    );
    const shasums = `${h}  skillz-darwin-arm64\n`;
    const { dir, binaryPath, shasumsPath } = await setup(shasums, payload);
    try {
      const r = await verifyBinaryAgainstShasums(
        binaryPath,
        "skillz-darwin-arm64",
        shasumsPath,
      );
      expect(r.kind).toBe("ok");
      if (r.kind === "ok") expect(r.hash).toBe(h);
    } finally {
      await fs.rm(dir, { recursive: true, force: true });
    }
  });

  test("returns mismatch when the binary has been tampered with", async () => {
    const shasums = `${"a".repeat(64)}  skillz-darwin-arm64\n`;
    const { dir, binaryPath, shasumsPath } = await setup(shasums, "tampered");
    try {
      const r = await verifyBinaryAgainstShasums(
        binaryPath,
        "skillz-darwin-arm64",
        shasumsPath,
      );
      expect(r.kind).toBe("mismatch");
      if (r.kind === "mismatch") {
        expect(r.expected).toBe("a".repeat(64));
        expect(r.got).not.toBe(r.expected);
        expect(r.got).toMatch(/^[0-9a-f]{64}$/);
      }
    } finally {
      await fs.rm(dir, { recursive: true, force: true });
    }
  });

  test("returns not-listed when the target filename is missing from SHASUMS", async () => {
    const shasums = `${"b".repeat(64)}  skillz-linux-x64\n`;
    const { dir, binaryPath, shasumsPath } = await setup(shasums, "x");
    try {
      const r = await verifyBinaryAgainstShasums(
        binaryPath,
        "skillz-darwin-arm64",
        shasumsPath,
      );
      expect(r.kind).toBe("not-listed");
    } finally {
      await fs.rm(dir, { recursive: true, force: true });
    }
  });

  test("returns missing-shasums when the file doesn't exist", async () => {
    const dir = await fs.mkdtemp(path.join(os.tmpdir(), "skillz-verify-"));
    const binaryPath = path.join(dir, "skillz-darwin-arm64");
    await fs.writeFile(binaryPath, "x");
    try {
      const r = await verifyBinaryAgainstShasums(
        binaryPath,
        "skillz-darwin-arm64",
        path.join(dir, "does-not-exist.txt"),
      );
      expect(r.kind).toBe("missing-shasums");
    } finally {
      await fs.rm(dir, { recursive: true, force: true });
    }
  });
});
